version: "3"

services:
  jupyterlab:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - $PWD/notebooks:/home/notebooks

  test:
    build: .
    volumes:
      - $PWD/:/home
    entrypoint: ["/venv/bin/pytest"]
