version: '3'

services:
  web:
    build: ../docker-jupyter-extended/
    #image: dynobo/docker-jupyter-extended:0.2.0 -s \"-screen 0 1400x900x24\"
    command: xvfb-run -e /dev/stdout start.sh jupyter lab
    
    ports:
      - "8888:8888"
    volumes:
      - $PWD/notebooks:/home/jovyan/notebooks